### ISSUE TITLE
March 12, 2017 Action Items

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#133]
Not adding consent to proceed. Only consent to implement items.

## @rapi-castillo 

- [ ] Add to Decision Making Policy: notify people based on channel membership and consent-giving process. #108
- [ ] State of the Network Address #105
- [ ] Change "Staffer" language to "Volunteer Staffer #95 
- [ ] Lessen the mentions of "Bernie" in the Manifesto #106 
- [ ] Remove mentions of supporting PACs at the ProgCode Manifesto #88 
- [ ] Addition of Zoom/Meeting tools to Common Good Funding at the Funding Framework #107 
- [ ] Open up Zoom and create a Calendly event-type for Partners team meeting #109 

## @jpb5013 

- [ ] Remote MeetUp Hack Night #116 

## @WoobieTuesday 

- [ ] App Partner onboarders unable to access Medium to Publish "Network Voices" #111
