### ISSUE TITLE
Action Items: March 26, 2017

### ISSUE THREAD

**Issue by rcscastillo** [ProgressiveCoders/functions#146]
Action Items from last meeting, March 26 2017

### @rapicastillo 
- [ ] Issue Focus: Single Payer Healthcare #142 
- [ ] Move Operations team meeting to Mondays @ 8pm ET #135 
- [ ] Set ProgCode as a project in CodeCorps #140
- [ ] Rhize #141 
- [ ] RISE #139 
- [ ] Review default channel descriptions and contact #138 

### @jpb5013 
- [ ] Review, gather feedback and update Onboarding process #143 
- [ ] Establish Editorial Review Process #129 

### @dave-mahler 
- [ ] Member Updates on Airtable #69 

### @ellenm 
- [ ] Review default channel descriptions and contact #138
