### ISSUE TITLE
Action Items: April 3, 2017

### ISSUE THREAD

**Issue by rcscastillo** [ProgressiveCoders/functions#170]
# Rapi

- [ ] Discussion/revision of contentious passage on how to deal with offenses in Community Guidelines #144
- [ ] Make Progressive Coders Slack open to public, make ProgCode entity separate from the network #137
- [ ] Discussion on what a member is #147 
- [ ] Discussion on who can vote on operational by-consent voting #148
- [ ] People's Summit #145
- [ ] toolkit.progcode.org #97 

# Joe
- [ ] Update Staff Decision and Change process #124 

# Jacob
- [ ] Reimbursement for The Arena Conference #149
